#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss-conflict-handling.name" . }}-db-br-agent-limit-internal-traffic
  labels:
    chart: {{ template "eric-oss-conflict-handling.chart" . }}
    {{- include "eric-oss-conflict-handling.kubernetes-io-info" .| nindent 4 }}
  annotations:
    {{- include "eric-oss-conflict-handling.product-info" .| indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-conflict-manager-database-pg-bragent
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-oss-conflict-manager-database-pg
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-ctrl-bro
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-pm-server
